In [43]:
import os
import numpy as np
import rasterio
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [44]:
df= pd.read_csv('OMSdf_TA_20072008.csv',sep=',',skiprows=1,low_memory=False)
df

@H         timestamp  val_1133  val_1135  val_1141  val_1148  \
0      val                      1133.0    1135.0    1141.0    1148.0   
1      NaN  2007-01-01 00:00   -9999.0   -9999.0   -9999.0   -9999.0   
2      NaN  2007-01-01 01:00   -9999.0   -9999.0   -9999.0   -9999.0   
3      NaN  2007-01-01 02:00   -9999.0   -9999.0   -9999.0   -9999.0   
4      NaN  2007-01-01 03:00   -9999.0   -9999.0   -9999.0   -9999.0   
5      NaN  2007-01-01 04:00   -9999.0   -9999.0   -9999.0   -9999.0   
6      NaN  2007-01-01 05:00   -9999.0   -9999.0   -9999.0   -9999.0   
7      NaN  2007-01-01 06:00   -9999.0   -9999.0   -9999.0   -9999.0   
8      NaN  2007-01-01 07:00   -9999.0   -9999.0   -9999.0   -9999.0   
9      NaN  2007-01-01 08:00   -9999.0   -9999.0   -9999.0   -9999.0   
10     NaN  2007-01-01 09:00   -9999.0   -9999.0   -9999.0   -9999.0   
11     NaN  2007-01-01 10:00   -9999.0   -9999.0   -9999.0   -9999.0   
12     NaN  2007-01-01 11:00   -9999.0   -9999.0   -9999.0   -9999.0   
13     NaN  2007-01-01 12:00   -9999.0   -9999.0   -9999.0   -9999.0   
14     NaN  2007-01-01 13:00   -9999.0   -9999.0   -9999.0   -9999.0   
15     NaN  2007-01-01 14:00   -9999.0   -9999.0   -9999.0   -9999.0   
16     NaN  2007-01-01 15:00   -9999.0   -9999.0   -9999.0   -9999.0   
17     NaN  2007-01-01 16:00   -9999.0   -9999.0   -9999.0   -9999.0   
18     NaN  2007-01-01 17:00   -9999.0   -9999.0   -9999.0   -9999.0   
19     NaN  2007-01-01 18:00   -9999.0   -9999.0   -9999.0   -9999.0   
20     NaN  2007-01-01 19:00   -9999.0   -9999.0   -9999.0   -9999.0   
21     NaN  2007-01-01 20:00   -9999.0   -9999.0   -9999.0   -9999.0   
22     NaN  2007-01-01 21:00   -9999.0   -9999.0   -9999.0   -9999.0   
23     NaN  2007-01-01 22:00   -9999.0   -9999.0   -9999.0   -9999.0   
24     NaN  2007-01-01 23:00   -9999.0   -9999.0   -9999.0   -9999.0   
25     NaN  2007-01-02 00:00   -9999.0   -9999.0   -9999.0   -9999.0   
26     NaN  2007-01-02 01:00   -9999.0   -9999.0   -9999.0   -9999.0   
27     NaN  2007-01-02 02:00   -9999.0   -9999.0   -9999.0   -9999.0   
28     NaN  2007-01-02 03:00   -9999.0   -9999.0   -9999.0   -9999.0   
29     NaN  2007-01-02 04:00   -9999.0   -9999.0   -9999.0   -9999.0   
...    ...               ...       ...       ...       ...       ...   
17514  NaN  2008-12-30 17:00   -9999.0   -9999.0   -9999.0   -9999.0   
17515  NaN  2008-12-30 18:00   -9999.0   -9999.0   -9999.0   -9999.0   
17516  NaN  2008-12-30 19:00   -9999.0   -9999.0   -9999.0   -9999.0   
17517  NaN  2008-12-30 20:00   -9999.0   -9999.0   -9999.0   -9999.0   
17518  NaN  2008-12-30 21:00   -9999.0   -9999.0   -9999.0   -9999.0   
17519  NaN  2008-12-30 22:00   -9999.0   -9999.0   -9999.0   -9999.0   
17520  NaN  2008-12-30 23:00   -9999.0   -9999.0   -9999.0   -9999.0   
17521  NaN  2008-12-31 00:00   -9999.0   -9999.0   -9999.0   -9999.0   
17522  NaN  2008-12-31 01:00   -9999.0   -9999.0   -9999.0   -9999.0   
17523  NaN  2008-12-31 02:00   -9999.0   -9999.0   -9999.0   -9999.0   
17524  NaN  2008-12-31 03:00   -9999.0   -9999.0   -9999.0   -9999.0   
17525  NaN  2008-12-31 04:00   -9999.0   -9999.0   -9999.0   -9999.0   
17526  NaN  2008-12-31 05:00   -9999.0   -9999.0   -9999.0   -9999.0   
17527  NaN  2008-12-31 06:00   -9999.0   -9999.0   -9999.0   -9999.0   
17528  NaN  2008-12-31 07:00   -9999.0   -9999.0   -9999.0   -9999.0   
17529  NaN  2008-12-31 08:00   -9999.0   -9999.0   -9999.0   -9999.0   
17530  NaN  2008-12-31 09:00   -9999.0   -9999.0   -9999.0   -9999.0   
17531  NaN  2008-12-31 10:00   -9999.0   -9999.0   -9999.0   -9999.0   
17532  NaN  2008-12-31 11:00   -9999.0   -9999.0   -9999.0   -9999.0   
17533  NaN  2008-12-31 12:00   -9999.0   -9999.0   -9999.0   -9999.0   
17534  NaN  2008-12-31 13:00   -9999.0   -9999.0   -9999.0   -9999.0   
17535  NaN  2008-12-31 14:00   -9999.0   -9999.0   -9999.0   -9999.0   
17536  NaN  2008-12-31 15:00   -9999.0   -9999.0   -9999.0   -9999.0   
17537  NaN  2008-12-31 16:00   -9999.0   -9999.0

In [55]:
Data = df.iloc[1:,1:]
Data = Data.set_index('timestamp')
Data

val_1133  val_1135  val_1141  val_1148  val_1151  val_90029  \
timestamp                                                                       
2007-01-01 00:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -5.0   
2007-01-01 01:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -4.3   
2007-01-01 02:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -4.7   
2007-01-01 03:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -5.2   
2007-01-01 04:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -5.3   
2007-01-01 05:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -5.4   
2007-01-01 06:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -6.4   
2007-01-01 07:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -6.3   
2007-01-01 08:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -6.8   
2007-01-01 09:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -7.2   
2007-01-01 10:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -7.1   
2007-01-01 11:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -7.3   
2007-01-01 12:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -7.4   
2007-01-01 13:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -7.4   
2007-01-01 14:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -7.5   
2007-01-01 15:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0       -7.9   
2007-01-01 16:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -10.2   
2007-01-01 17:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -11.3   
2007-01-01 18:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -12.4   
2007-01-01 19:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -13.8   
2007-01-01 20:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -14.6   
2007-01-01 21:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -15.3   
2007-01-01 22:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -15.7   
2007-01-01 23:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -14.6   
2007-01-02 00:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -13.5   
2007-01-02 01:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -13.6   
2007-01-02 02:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -14.5   
2007-01-02 03:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -15.7   
2007-01-02 04:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -15.4   
2007-01-02 05:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -15.8   
...                    ...       ...       ...       ...       ...        ...   
2008-12-30 17:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -11.5   
2008-12-30 18:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -11.5   
2008-12-30 19:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -12.0   
2008-12-30 20:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -12.0   
2008-12-30 21:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -11.9   
2008-12-30 22:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -11.9   
2008-12-30 23:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -11.8   
2008-12-31 00:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -12.0   
2008-12-31 01:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -12.3   
2008-12-31 02:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -12.5   
2008-12-31 03:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -12.5   
2008-12-31 04:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -13.0   
2008-12-31 05:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -13.4   
2008-12-31 06:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -13.1   
2008-12-31 07:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -13.4   
2008-12-31 08:00   -9999.0   -9999.0   -9999.0   -9999.0   -9999.0      -13.4   
2008-12-31 09:00   -9999.0   -9999.0   -9999.0   

In [98]:
Data2 = Data.values

In [99]:
Data2[Data2 == -9999]= np.nan

In [100]:
Data2

array([[ nan,  nan,  nan, ..., -2.5,  1.3,  0. ],
       [ nan,  nan,  nan, ..., -2.1,  0.7,  0. ],
       [ nan,  nan,  nan, ..., -1.4,  0.5,  0. ],
       ...,
       [ nan,  nan,  nan, ..., -6. , -4.6, -9.2],
       [ nan,  nan,  nan, ..., -5.6, -4.6, -9.2],
       [ nan,  nan,  nan, ..., -6.3, -5.3, -9.1]])

In [102]:
np.nanmean(Data2[0:(30*24),:], axis=0)

array([  0.25024876,  -8.31580189,  -7.45165094,  -3.01627358,
       -11.60495283, -10.55180556,  -6.43125   ,  -2.81569444,
        -3.27125   ,  -5.34652778,  -3.08541667,  -1.46888889,
        -1.21569444,   1.30152778,  -0.46722222,   0.97125   ,
        -0.32638889,   1.90652778,  -0.72277778,   1.3225    ,
         0.        ])

In [103]:
month =[0,31,28,31,30,31,30,31,31,30,31,30,31]
month2hours = np.array(month)*24
month2hours

array([  0, 744, 672, 744, 720, 744, 720, 744, 744, 720, 744, 720, 744])

In [115]:
for count in range(0,12):
    month2hours[count]#,month2hours[count+1]]
    b = np.nanmean(Data2[month2hours[count]:month2hours[count+1],:], axis=0)
    a[count,:] = b[:,:]
    #b =  month[count+1]#(30*24)*(count+1)
   # print(a)
   # print(mimmo)


IndexError: too many indices for array

In [109]:
mimmo = Data2[month2hours[count]:month2hours[count+1],:]

In [110]:
mimmo

array([[ nan,  nan,  nan,  nan,  nan, -5. , -1.2, -3.5,  1.8, -1. , -2.6,
        -3.2, -2.4,  0.2,  0. , -2.4, -4.3, -1.5, -2.5,  1.3,  0. ],
       [ nan,  nan,  nan,  nan,  nan, -4.3, -0.1, -2.5,  1.5, -0.6, -2.5,
        -3.3, -2.7, -0.1,  1.3, -2.1, -3.7, -1.6, -2.1,  0.7,  0. ],
       [ nan,  nan,  nan,  nan,  nan, -4.7, -0.5, -2.5,  2. , -1.3, -2. ,
        -3.9, -2.9, -0.7,  1.4, -1.6, -3.2, -1.3, -1.4,  0.5,  0. ],
       [ nan,  nan,  nan,  nan,  nan, -5.2, -1.1, -2.9,  1.2, -1.3, -2.5,
        -3.6, -3.1, -0.1,  1.4, -0.9, -2.9, -1. , -0.7,  0.6,  0. ]])